spring:
  application:
    name: api-gateway

  cloud:
    config:
      uri: http://config.platform:9000  # Config Server URL

server:
  port: 8080  # Gateway port (change if needed)

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true